DROP DATABASE IF EXISTS my_first_triggers_db;
CREATE DATABASE my_first_triggers_db;
USE my_first_triggers_db;

CREATE TABLE DEPT(
	DEPTNO INT(2) NOT NULL,
	DNAME VARCHAR(14), 
    LOC VARCHAR(14)
    );
 
CREATE TABLE EMP(
	EMPNO INT(4) NOT NULL,
	ENAME VARCHAR(10),
    JOB VARCHAR(25),
	HIREDATE DATE,
    MGR INT(4), 
    SAL FLOAT(7,2), 
    COMM FLOAT(7,2),
	DEPTNO INT(2)
    );

INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES 
	(10, 'ACCOUNTING', 'ATHENS');
    
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES 
	(20, 'SALES', 'LONDON');
    
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES 
	(30, 'RESEARCH', 'ATHENS');

INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES 
	(40, 'PAYROLL', 'LONDON');
    
INSERT INTO EMP VALUES 
	(10, 'CODD', 'ANALYST', '1989/01/01', 15, 3000, NULL, 10);
    
INSERT INTO EMP VALUES
	(15, 'ELMASRI', 'ANALYST', '1995/05/02', 15, 1200, 150,10);
    
INSERT INTO EMP VALUES 
	(20, 'NAVATHE', 'SALESMAN', '1977/07/07', 20, 2000, NULL, 20);

INSERT INTO EMP VALUES 
	(30, 'DATE', 'PROGRAMMER', '2004/05/04', 15, 1800, 200,10);
    
    
CREATE VIEW SUMS (department, mini, maxi) AS     
    SELECT DEPT.DNAME, MIN(EMP.SAL), MAX(EMP.SAL) FROM EMP JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO GROUP BY DEPT.DNAME;

SELECT * FROM SUMS;
    

    


    
    