name: Publish release

on:
  push:
    tags:
      - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Tag Name
        id: tag_name
        run: |
          if [[ "${GITHUB_REF}" == "refs/tags/"* ]]; then
            echo "::set-output name=tag_name::$(basename ${GITHUB_REF})"
          else
            echo "::set-output name=tag_name::"
          fi
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          release_name: Release ${{ steps.tag_name.outputs.tag_name }}
          draft: false
          prerelease: false
      - name: Zip directories
        run: |
          for dir in */; do
            zip -r "${dir%/}.zip" "$dir"
          done
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.zip
          asset_name: uniwa-${{ steps.tag_name.outputs.tag_name }}.zip
          asset_content_type: application/zip

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.6.1
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: "*.zip"
          tag: ${{ steps.tag_name.outputs.tag_name }}
          file_glob: true
          release_name: "Uni Notes ${{ steps.tag_name.outputs.tag_name }}"
          body: "My university notes and personal guides"
